server:
  port: 8081
  netty:
    idle-timeout: 30s
spring:
  main:
    web-application-type: reactive
  application:
    name: "text-nequi-franchises"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/franchises_db
    username: postgres
    password: root
    schema: public
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"


# Habilitar nivel de log DEBUG para Spring WebFlux y Reactor
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.core.publisher: DEBUG
    org.springframework.boot.actuate: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG
