server:
  port: 8081
spring:
  application:
    name: "Franchises"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/franchises_db
    username: postgres
    password: root
    schema: public
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"
